server:
  port: 8071

spring:
  dubbo:
    application: item-service
    protocol:
      name: dubbo
    registry:
      address: zookeeper://192.168.116.146:2181
      protocol: zookeeper
    base-package: com.su.item
    consumer:
      timeout: 60000
      check: false


