
server:
  port: 8070


spring:
  datasource:
    url: jdbc:mysql://192.168.116.146:3306/mall?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootss


  dubbo:
    application: user-service
    protocol:
      name: dubbo
    registry:
      address: zookeeper://192.168.116.146:2181
      protocol: zookeeper
    base-package: com.su.manage


logging:
  level:
    com.su.manage.mapper: debug
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml




